version: "3"

services:
  postgres:
    image: postgres:16.0.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: productdatabase